version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bank-store
      POSTGRES_PASSWORD: bank-store
      POSTGRES_DB: bank-store
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
